version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install'
    # steps:
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'prebuild'
      - aws ecr get-login-password --region us-east-1 --profile guru | docker login --username AWS --password-stdin 029887954252.dkr.ecr.us-east-1.amazona
    # steps:
  build:
    on-failure: ABORT
    commands:
      - echo 'build'
      - docker build -t $IMAGE .
      - docker tag prod-$IMAGE:$TAG $REPOSITORY/prod-laravel-api-base-image:latest
    # steps:
  post_build:

    on-failure: ABORT
    commands:
      - echo 'postbuild'
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$TAG


